-- =============================================================================
-- FEU LFMS — Seed data
-- Loads after schema.sql. Idempotent if you DELETE FROM tables first.
--
-- All seed accounts share the password: "password123"
-- The bcrypt hash below was generated by:
--   php -r "echo password_hash('password123', PASSWORD_DEFAULT) . PHP_EOL;"
--
-- IMPORTANT: regenerate this hash on your machine before deploying to anything
-- non-development. See db/hash_passwords.php for the generator.
-- =============================================================================

SET @pw := '$2y$10$xUomOqidr7wzDQ2kF0z5EObWMhDPyyB6I6dLQaq3k3N0Wb6FW4IZm';
SET NAMES utf8mb4;


-- -----------------------------------------------------------------------------
-- accounts (1 admin · 2 staff · 4 students · 1 faculty)
-- -----------------------------------------------------------------------------
INSERT INTO accounts (role, user_type, full_name, id_number, email, password_hash, is_active) VALUES
  ('admin', NULL,       'Admin User',          'ADMIN-001',     'admin@feu.edu.ph',           @pw, 1),
  ('staff', NULL,       'Alice Reyes',         'STAFF-001',     'alice.reyes@feu.edu.ph',     @pw, 1),
  ('staff', NULL,       'Bob Santos',          'STAFF-002',     'bob.santos@feu.edu.ph',      @pw, 1),
  ('user',  'student',  'Juan Dela Cruz',      '2024-00001',    'juan.delacruz@feu.edu.ph',   @pw, 1),
  ('user',  'student',  'Maria Santos',        '2024-00002',    'maria.santos@feu.edu.ph',    @pw, 1),
  ('user',  'student',  'Pedro Gomez',         '2024-00003',    'pedro.gomez@feu.edu.ph',     @pw, 1),
  ('user',  'student',  'Ana Lopez',           '2024-00004',    'ana.lopez@feu.edu.ph',       @pw, 1),
  ('user',  'faculty',  'Prof. Luis Tan',      '2020-EMP-001',  'luis.tan@feu.edu.ph',        @pw, 1);


-- -----------------------------------------------------------------------------
-- storage_locations
-- -----------------------------------------------------------------------------
INSERT INTO storage_locations (code, description, is_active) VALUES
  ('BIN-A-1',   'Front Desk Bin A, Shelf 1 (small items)',           1),
  ('BIN-A-2',   'Front Desk Bin A, Shelf 2 (bags & containers)',     1),
  ('SHELF-B-1', 'Back Office Shelf B, Level 1 (valuables, locked)',  1);


-- -----------------------------------------------------------------------------
-- settings — admin-configurable runtime values
-- -----------------------------------------------------------------------------
INSERT INTO settings (key_name, value) VALUES
  ('holding_period_days',     '365'),
  ('match_threshold',         '30'),
  ('match_weight_category',   '30'),
  ('match_weight_color',      '20'),
  ('match_weight_location',   '15'),
  ('match_weight_date',       '10'),
  ('match_weight_description','25'),
  ('upload_max_bytes',        '4194304'),
  ('notify_poll_seconds',     '60');


-- -----------------------------------------------------------------------------
-- lost_reports (4 reports from 4 different students)
-- -----------------------------------------------------------------------------
INSERT INTO lost_reports
  (ref_number,           reporter_account_id, category,     color,   brand,        description,                                                  last_seen_location,             date_lost,    status,    is_suspicious)
VALUES
  ('LFMS-2026-00001', 4, 'bag',         'navy',  'Jansport',   'Navy blue Jansport backpack with a small FEU sticker on the front flap.',   '3rd floor study area',         '2026-05-10', 'open',    0),
  ('LFMS-2026-00002', 5, 'phone',       'black', 'Apple',      'Black iPhone 14 with a cracked top-right corner of the screen.',            '2nd floor reading lounge',     '2026-05-12', 'open',    0),
  ('LFMS-2026-00003', 6, 'calculator',  'black', 'Casio',      'Casio fx-991ES PLUS scientific calculator. Name "P. Gomez" on the back.',   'Reference section',            '2026-05-08', 'open',    0),
  ('LFMS-2026-00004', 7, 'water bottle','pink',  'Hydro Flask','Pink Hydro Flask 32oz with assorted stickers (band logos, FEU Tamaraw).',   'Cafe area outside library',    '2026-05-15', 'open',    0);


-- -----------------------------------------------------------------------------
-- found_reports (3 found items logged by staff)
-- Item #1 closely matches lost_report #1 — used for the seeded match below.
-- -----------------------------------------------------------------------------
INSERT INTO found_reports
  (ref_number,             finder_account_id, category, color,   brand,        description,                                                       storage_location_id, date_found,  status)
VALUES
  ('LFMS-2026-F-00001', 2, 'bag',      'navy',  'Jansport',   'Navy blue Jansport backpack, FEU sticker on flap, contains notebooks.',          2, '2026-05-11', 'open'),
  ('LFMS-2026-F-00002', 3, 'umbrella', 'black', NULL,         'Standard black foldable umbrella, no markings.',                                  1, '2026-05-13', 'open'),
  ('LFMS-2026-F-00003', 2, 'wallet',   'brown', NULL,         'Brown leather bi-fold wallet. Contents not inspected; sealed in evidence bag.',   3, '2026-05-14', 'open');


-- -----------------------------------------------------------------------------
-- matches (1 sample match — pending staff validation)
-- Score 76 = category(30) + color(20) + location(0) + date(10) + description(16)
-- Values match what lib/matching.php would actually compute for this pair
-- (Jaccard description: 7 shared tokens / 11 union ≈ 0.636 × weight 25 = 16).
-- Re-running generate_candidates_for_found(1) after import is a no-op.
-- -----------------------------------------------------------------------------
INSERT INTO matches
  (lost_report_id, found_report_id, score, factors_json, status, is_suspicious)
VALUES
  (1, 1, 76,
   JSON_OBJECT('category', 30, 'color', 20, 'location', 0, 'date', 10, 'description', 16),
   'pending', 0);


-- -----------------------------------------------------------------------------
-- notifications (1 unread, demonstrates the bell badge)
-- -----------------------------------------------------------------------------
INSERT INTO notifications
  (recipient_account_id, type, title, body, link_url, is_read)
VALUES
  (4, 'match.proposed',
   'A possible match was found for your lost item.',
   'Library staff found a navy Jansport backpack that may be yours. Once staff confirm the match, you will be able to submit a claim. Reference: LFMS-2026-00001.',
   '/index.php?p=lost.show&id=1',
   0);


-- -----------------------------------------------------------------------------
-- audit_logs (a few entries so the Admin Audit Log has content to display)
-- -----------------------------------------------------------------------------
INSERT INTO audit_logs
  (actor_account_id, action,                  target_type,    target_id, diff_json,                                                   ip_address)
VALUES
  (4, 'lost_report.create',  'lost_report',  1, JSON_OBJECT('status', JSON_ARRAY(NULL, 'open')),     '127.0.0.1'),
  (5, 'lost_report.create',  'lost_report',  2, JSON_OBJECT('status', JSON_ARRAY(NULL, 'open')),     '127.0.0.1'),
  (6, 'lost_report.create',  'lost_report',  3, JSON_OBJECT('status', JSON_ARRAY(NULL, 'open')),     '127.0.0.1'),
  (7, 'lost_report.create',  'lost_report',  4, JSON_OBJECT('status', JSON_ARRAY(NULL, 'open')),     '127.0.0.1'),
  (2, 'found_report.create', 'found_report', 1, JSON_OBJECT('status', JSON_ARRAY(NULL, 'open')),     '127.0.0.1'),
  (3, 'found_report.create', 'found_report', 2, JSON_OBJECT('status', JSON_ARRAY(NULL, 'open')),     '127.0.0.1'),
  (2, 'found_report.create', 'found_report', 3, JSON_OBJECT('status', JSON_ARRAY(NULL, 'open')),     '127.0.0.1'),
  (NULL, 'match.generate',   'match',        1, JSON_OBJECT('score', 76, 'factors', JSON_OBJECT('category',30,'color',20,'location',0,'date',10,'description',16)), NULL);
