<?php
declare(strict_types=1);

/**
 * Admin report detail — computes and displays a previously generated report.
 *
 * The `reports` table stores only metadata (type, parameters, who/when).
 * The data is computed on-demand here each time the report is viewed.
 *
 * Supported types:
 *   operational_summary  — lost/found totals, match rate, claim rate by status
 *   match_effectiveness  — score distribution, avg time from found to matched
 *   user_activity        — top reporters: lost/found/claim counts per account
 */

$id = (int) ($_GET['id'] ?? 0);
if ($id <= 0) {
    http_response_code(404);
    require __DIR__ . '/404.php';
    exit;
}

$report = q_one(
    'SELECT reports.*, accounts.full_name AS generated_by
       FROM reports
       JOIN accounts ON accounts.id = reports.generated_by_account_id
      WHERE reports.id = ? LIMIT 1',
    [$id]
);

if ($report === null) {
    http_response_code(404);
    require __DIR__ . '/404.php';
    exit;
}

$params = json_decode((string) $report['parameters_json'], true) ?? [];
$from   = (string) ($params['date_from'] ?? '');
$to     = (string) ($params['date_to'] ?? '');
$type   = (string) $report['report_type'];

$title_map = [
    'operational_summary' => 'Operational Summary',
    'match_effectiveness' => 'Match Effectiveness',
    'user_activity'       => 'User Activity',
];

// -----------------------------------------------------------------------------
// CSV export branch — fires before any HTML output.
// -----------------------------------------------------------------------------
if (($_GET['format'] ?? '') === 'csv') {
    $range_from = $from . ' 00:00:00';
    $range_to   = $to   . ' 23:59:59';
    $filename   = sprintf('lfms-%s-%s-to-%s.csv', $type, $from, $to);

    csv_send($filename, function ($h) use ($type, $report, $from, $to, $range_from, $range_to, $title_map) {
        csv_row($h, ['FEU Library — Lost & Found Management System']);
        csv_row($h, ['Report', $title_map[$type] ?? $type]);
        csv_row($h, ['Period', $from . ' to ' . $to]);
        csv_row($h, ['Generated by', (string) $report['generated_by']]);
        csv_row($h, ['Generated at', (string) $report['generated_at']]);
        csv_row($h, []);

        if ($type === 'operational_summary') {
            $lost_total  = (int) (q_value("SELECT COUNT(*) FROM lost_reports  WHERE created_at BETWEEN ? AND ?", [$range_from, $range_to]) ?? 0);
            $found_total = (int) (q_value("SELECT COUNT(*) FROM found_reports WHERE created_at BETWEEN ? AND ?", [$range_from, $range_to]) ?? 0);
            $match_total = (int) (q_value("SELECT COUNT(*) FROM matches       WHERE created_at BETWEEN ? AND ?", [$range_from, $range_to]) ?? 0);
            $approved    = (int) (q_value("SELECT COUNT(*) FROM matches       WHERE status = 'approved' AND created_at BETWEEN ? AND ?", [$range_from, $range_to]) ?? 0);
            $released    = (int) (q_value("SELECT COUNT(*) FROM claim_tickets WHERE status = 'released' AND created_at BETWEEN ? AND ?", [$range_from, $range_to]) ?? 0);
            // Count from audit_logs so later edits to the row don't shift the
            // count out of the report period (found_reports.updated_at bumps
            // on every UPDATE; audit row's created_at is the actual expiry).
            $expired     = (int) (q_value("SELECT COUNT(*) FROM audit_logs WHERE action = 'found_report.expire' AND created_at BETWEEN ? AND ?", [$range_from, $range_to]) ?? 0);

            $match_rate = $lost_total > 0 ? round($approved / $lost_total * 100, 1) : 0;
            $claim_rate = $approved  > 0 ? round($released  / $approved  * 100, 1) : 0;

            csv_section($h, 'Totals', ['Metric', 'Count'], [
                ['Lost reports',                 $lost_total],
                ['Found items',                  $found_total],
                ['Matches proposed',             $match_total],
                ['Matches approved',             $approved],
                ['Items released',               $released],
                ['Items expired without claim',  $expired],
            ]);

            csv_section($h, 'Rates', ['Metric', 'Value'], [
                ['Match rate (approved / lost reports)', $match_rate . '%'],
                ['Claim conversion (released / approved matches)', $claim_rate . '%'],
            ]);

            $by_status = q_all(
                'SELECT status, COUNT(*) AS cnt FROM lost_reports
                  WHERE created_at BETWEEN ? AND ?
                 GROUP BY status ORDER BY cnt DESC',
                [$range_from, $range_to]
            );
            $rows = array_map(fn($r) => [(string) $r['status'], (int) $r['cnt']], $by_status);
            csv_section($h, 'Lost reports by status', ['Status', 'Count'], $rows);
        }

        elseif ($type === 'match_effectiveness') {
            $score_dist = q_all(
                'SELECT FLOOR(score / 10) * 10 AS bucket, COUNT(*) AS cnt
                   FROM matches WHERE created_at BETWEEN ? AND ?
                  GROUP BY bucket ORDER BY bucket DESC',
                [$range_from, $range_to]
            );
            $rows = array_map(function ($r) {
                $b = (int) $r['bucket'];
                return [$b . '-' . min(100, $b + 9), (int) $r['cnt']];
            }, $score_dist);
            csv_section($h, 'Score distribution', ['Score range', 'Count'], $rows);

            $avg_days = q_value(
                'SELECT AVG(DATEDIFF(matches.created_at, found_reports.date_found))
                   FROM matches
                   JOIN found_reports ON found_reports.id = matches.found_report_id
                  WHERE matches.created_at BETWEEN ? AND ?',
                [$range_from, $range_to]
            );
            csv_section($h, 'Match metadata', ['Metric', 'Value'], [
                ['Avg days from found to match proposed',
                 $avg_days !== null ? round((float) $avg_days, 1) . ' days' : ''],
            ]);

            $status_dist = q_all(
                'SELECT status, COUNT(*) AS cnt FROM matches
                  WHERE created_at BETWEEN ? AND ?
                 GROUP BY status ORDER BY cnt DESC',
                [$range_from, $range_to]
            );
            $rows = array_map(fn($r) => [(string) $r['status'], (int) $r['cnt']], $status_dist);
            csv_section($h, 'Matches by status', ['Status', 'Count'], $rows);
        }

        elseif ($type === 'user_activity') {
            $top_reporters = q_all(
                'SELECT accounts.full_name, accounts.id_number, accounts.role,
                        COUNT(DISTINCT lost_reports.id) AS lost_count
                   FROM accounts
                   LEFT JOIN lost_reports ON lost_reports.reporter_account_id = accounts.id
                       AND lost_reports.created_at BETWEEN ? AND ?
                  WHERE accounts.role = ?
                  GROUP BY accounts.id
                  ORDER BY lost_count DESC
                  LIMIT 20',
                [$range_from, $range_to, 'user']
            );
            $rows = [];
            foreach ($top_reporters as $r) {
                if ((int) $r['lost_count'] === 0) continue;
                $rows[] = [(string) $r['full_name'], (string) $r['id_number'], (int) $r['lost_count']];
            }
            csv_section($h, 'Top reporters', ['Name', 'ID number', 'Lost reports filed'], $rows);
        }

        else {
            csv_row($h, ['Unknown report type', $type]);
        }
    });
}

layout_open($title_map[$type] ?? ucwords(str_replace('_', ' ', $type)));

breadcrumb([
    ['Dashboard', url('/index.php?p=admin.dashboard')],
    ['Reports',   url('/index.php?p=admin.reports')],
    [$title_map[$type] ?? 'Report'],
]);

$export_url = url('/index.php?p=admin.report.show&id=' . $id . '&format=csv');
page_header(
    ($title_map[$type] ?? ucwords(str_replace('_', ' ', $type))) . ' Report',
    '<a class="btn btn-primary" href="' . e($export_url) . '">Export CSV</a>'
    . ' <a class="btn btn-ghost" href="' . e(url('/index.php?p=admin.reports')) . '">Generate another</a>'
);
?>

<div class="card" style="margin-bottom: var(--card-gap);">
  <dl class="detail-grid">
    <dt>Period</dt>
    <dd><?= e($from) ?> &ndash; <?= e($to) ?></dd>
    <dt>Generated by</dt>
    <dd><?= e((string) $report['generated_by']) ?></dd>
    <dt>Generated at</dt>
    <dd><?= e(date('F j, Y g:i A', strtotime((string) $report['generated_at']))) ?></dd>
  </dl>
</div>

<?php

// =============================================================================
// Operational Summary
// =============================================================================
if ($type === 'operational_summary'):
    $lost_total   = (int) (q_value("SELECT COUNT(*) FROM lost_reports  WHERE created_at BETWEEN ? AND ?", [$from . ' 00:00:00', $to . ' 23:59:59']) ?? 0);
    $found_total  = (int) (q_value("SELECT COUNT(*) FROM found_reports WHERE created_at BETWEEN ? AND ?", [$from . ' 00:00:00', $to . ' 23:59:59']) ?? 0);
    $match_total  = (int) (q_value("SELECT COUNT(*) FROM matches       WHERE created_at BETWEEN ? AND ?", [$from . ' 00:00:00', $to . ' 23:59:59']) ?? 0);
    $approved     = (int) (q_value("SELECT COUNT(*) FROM matches       WHERE status = 'approved' AND created_at BETWEEN ? AND ?", [$from . ' 00:00:00', $to . ' 23:59:59']) ?? 0);
    $released     = (int) (q_value("SELECT COUNT(*) FROM claim_tickets WHERE status = 'released' AND created_at BETWEEN ? AND ?", [$from . ' 00:00:00', $to . ' 23:59:59']) ?? 0);
    $expired      = (int) (q_value("SELECT COUNT(*) FROM audit_logs WHERE action = 'found_report.expire' AND created_at BETWEEN ? AND ?", [$from . ' 00:00:00', $to . ' 23:59:59']) ?? 0);

    $match_rate   = $lost_total > 0 ? round($approved / $lost_total * 100, 1) : 0;
    $claim_rate   = $approved  > 0 ? round($released  / $approved  * 100, 1) : 0;
?>
  <section class="card">
    <div class="stat-strip">
      <div class="stat-card"><div class="stat-card-value"><?= $lost_total ?></div><div class="stat-card-label">Lost Reports</div></div>
      <div class="stat-card"><div class="stat-card-value"><?= $found_total ?></div><div class="stat-card-label">Found Items</div></div>
      <div class="stat-card"><div class="stat-card-value"><?= $approved ?></div><div class="stat-card-label">Matches Approved</div></div>
      <div class="stat-card"><div class="stat-card-value"><?= $released ?></div><div class="stat-card-label">Items Released</div></div>
    </div>
  </section>

  <section class="card" aria-labelledby="rates-title">
    <h2 class="card-title" id="rates-title">Rates</h2>
    <dl class="detail-grid">
      <dt>Match rate (approved / lost reports)</dt><dd><?= $match_rate ?>%</dd>
      <dt>Claim conversion (released / approved matches)</dt><dd><?= $claim_rate ?>%</dd>
      <dt>Total matches proposed</dt><dd><?= $match_total ?></dd>
      <dt>Items expired without claim</dt><dd><?= $expired ?></dd>
    </dl>
  </section>

  <?php
    $by_status = q_all(
        'SELECT status, COUNT(*) AS cnt FROM lost_reports
          WHERE created_at BETWEEN ? AND ?
         GROUP BY status ORDER BY cnt DESC',
        [$from . ' 00:00:00', $to . ' 23:59:59']
    );
  ?>
  <section class="card" aria-labelledby="status-title">
    <h2 class="card-title" id="status-title">Lost reports by status</h2>
    <div class="table-wrap">
      <table class="data-table">
        <thead><tr><th>Status</th><th class="col-narrow">Count</th></tr></thead>
        <tbody>
          <?php foreach ($by_status as $row): ?>
            <tr>
              <td><?= status_badge((string) $row['status']) ?></td>
              <td class="col-narrow"><?= (int) $row['cnt'] ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </section>

<?php
// =============================================================================
// Match Effectiveness
// =============================================================================
elseif ($type === 'match_effectiveness'):
    $score_dist = q_all(
        'SELECT FLOOR(score / 10) * 10 AS bucket, COUNT(*) AS cnt
           FROM matches WHERE created_at BETWEEN ? AND ?
          GROUP BY bucket ORDER BY bucket DESC',
        [$from . ' 00:00:00', $to . ' 23:59:59']
    );

    $avg_days = q_value(
        'SELECT AVG(DATEDIFF(matches.created_at, found_reports.date_found))
           FROM matches
           JOIN found_reports ON found_reports.id = matches.found_report_id
          WHERE matches.created_at BETWEEN ? AND ?',
        [$from . ' 00:00:00', $to . ' 23:59:59']
    );

    $status_dist = q_all(
        'SELECT status, COUNT(*) AS cnt FROM matches
          WHERE created_at BETWEEN ? AND ?
         GROUP BY status ORDER BY cnt DESC',
        [$from . ' 00:00:00', $to . ' 23:59:59']
    );
?>
  <section class="card" aria-labelledby="score-dist-title">
    <h2 class="card-title" id="score-dist-title">Score distribution</h2>
    <div class="table-wrap">
      <table class="data-table">
        <thead><tr><th>Score range</th><th class="col-narrow">Count</th></tr></thead>
        <tbody>
          <?php foreach ($score_dist as $row): ?>
            <tr>
              <td><?= (int) $row['bucket'] ?>&ndash;<?= min(100, (int) $row['bucket'] + 9) ?></td>
              <td class="col-narrow"><?= (int) $row['cnt'] ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </section>

  <section class="card" aria-labelledby="match-meta-title">
    <h2 class="card-title" id="match-meta-title">Match metadata</h2>
    <dl class="detail-grid">
      <dt>Avg days from found to match proposed</dt>
      <dd><?= $avg_days !== null ? round((float) $avg_days, 1) . ' days' : '—' ?></dd>
    </dl>
  </section>

  <section class="card" aria-labelledby="match-status-title">
    <h2 class="card-title" id="match-status-title">Matches by status</h2>
    <div class="table-wrap">
      <table class="data-table">
        <thead><tr><th>Status</th><th class="col-narrow">Count</th></tr></thead>
        <tbody>
          <?php foreach ($status_dist as $row): ?>
            <tr>
              <td><?= status_badge((string) $row['status']) ?></td>
              <td class="col-narrow"><?= (int) $row['cnt'] ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </section>

<?php
// =============================================================================
// User Activity
// =============================================================================
elseif ($type === 'user_activity'):
    $top_reporters = q_all(
        'SELECT accounts.full_name, accounts.id_number, accounts.role,
                COUNT(DISTINCT lost_reports.id) AS lost_count
           FROM accounts
           LEFT JOIN lost_reports ON lost_reports.reporter_account_id = accounts.id
               AND lost_reports.created_at BETWEEN ? AND ?
          WHERE accounts.role = ?
          GROUP BY accounts.id
          ORDER BY lost_count DESC
          LIMIT 20',
        [$from . ' 00:00:00', $to . ' 23:59:59', 'user']
    );
?>
  <section class="card" aria-labelledby="user-activity-title">
    <h2 class="card-title" id="user-activity-title">Top reporters</h2>
    <div class="table-wrap">
      <table class="data-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>ID number</th>
            <th class="col-narrow">Lost reports filed</th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($top_reporters as $row): ?>
            <?php if ((int) $row['lost_count'] === 0) continue; ?>
            <tr>
              <td><?= e((string) $row['full_name']) ?></td>
              <td class="text-sm text-muted"><?= e((string) $row['id_number']) ?></td>
              <td class="col-narrow"><?= (int) $row['lost_count'] ?></td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </section>

<?php else: ?>
  <div class="card">
    <p class="text-muted">Unknown report type: <?= e($type) ?></p>
  </div>
<?php endif; ?>

<?php
layout_close();
